{{- if .Values.ingressroute.enabled -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: speedupdate
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`{{ .Values.ingressroute.host }}`) 
    kind: Rule
    services:
    - name: speedupdate
      port: 50051
{{- end }} 
