apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "speedupdate_chart.fullname" . }}
  labels:
    {{- include "speedupdate_chart.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 3Gi
