apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: speedupdate-pvc
  namespace: speedupdate
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 3Gi
