apiVersion: v1
kind: Service
metadata:
  name: speedupdate
  labels:
    {{- include "speedupdate_chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpport }}
      targetPort: 8080
      protocol: TCP
      name: http
    - port: {{ .Values.service.grpcport }}
      targetPort: 3000
      protocol: TCP
      name: grpc
    - port: {{ .Values.service.ftpport }}
      targetPort: 2121
      protocol: TCP
      name: ftp
    - port: {{ .Values.service.metricport }}
      targetPort: 3001
      protocol: TCP
      name: metrics
  selector:
    {{- include "speedupdate_chart.selectorLabels" . | nindent 4 }}
 
