apiVersion: v1
kind: Service
metadata:
  name: speedupdate
  labels:
    {{- include "speedupdate_chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8012
      protocol: TCP
      name: http
  selector:
    {{- include "speedupdate_chart.selectorLabels" . | nindent 4 }}
 
